# Dependencies
markdown:         kramdown 
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Deebul Nair
tagline:          Research Student, Dharmic, creative, enterpreneur
url:              http://deebuls.github.io
paginate:         1
baseurl:          /
author:
  name:           Deebul Nair
  url:            https://twitter.com/deebuls
  email:          deebuls@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/deebuls

gems:             ["emoji_for_jekyll"]
